spring.application.name=banking
spring.graphql.graphiql.enabled=true
spring.kafka.consumer.group-id=banking-operation-processor
spring.kafka.consumer.properties.spring.json.trusted.packages=com.showcase.banking.operation.infrastructure.messaging
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.showcase.banking.operation.infrastructure.messaging.BankingOperationEvent
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
